### ISSUE TITLE
Mismatch in test counts

### ISSUE THREAD

**Issue by blainekasten** [winterbe/jest-teamcity-reporter#8] opened 2017-01-12 17:38 UTC
I'm not sure where this could be going wrong. But this is what I'm seeing in TC.

Build tab:
![image](https://cloud.githubusercontent.com/assets/2916023/21900959/7e0d8806-d8bb-11e6-9014-6c0ca3f04afd.png)

Tests Tab:
![image](https://cloud.githubusercontent.com/assets/2916023/21900929/640e8efa-d8bb-11e6-9851-a409668496aa.png)

I'm curious why the Tests tab would only report **785** when jest reports **1128**

**Comment by richardscarrott** [comment] 2017-01-20 18:02
@blainekasten Do you use forceExit in jest?

**Comment by blainekasten** [comment] 2017-01-20 22:03
nope.

**Comment by winterbe** [comment] 2017-01-23 08:22
Hm, strange. Which Teamcity version do you use?

**Comment by blainekasten** [comment] 2017-01-23 16:37
TeamCity Enterprise 9.1.6 (build 37459)

**Comment by winterbe** [comment] 2017-01-23 16:43
Sorry, can't help on this one. I'm using TC Professional 10.0.1 and can't reproduce this problem.

Is it possible for you to test with latest TC 10 release?

**Comment by richardscarrott** [comment] 2017-01-26 12:37
Yeah we're seeing the same problem in TC 9.1

**Comment by blainekasten** [comment] 2017-01-26 14:42
@winterbe I have no control over our TC version. Is there anything we can do to help you support this version?

**Comment by winterbe** [comment] 2017-01-26 15:18
This Jest Reporter relies on the [TC build script interaction](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity). Maybe something has changed between TC9 and TC10 which causes the issue.

However the total test count is not reporter by this project, it's measured by TC. So I really don't know why it's not working in TC9. I also don't have a TC9 installation in order to reproduce the issue.

You should check the TC Youtrack for open bugs regarding reported test count. Also feel free to debug this for your own. Feel free to send a PR if you find a fix.

**Comment by ToshB** [comment] 2017-03-22 13:13
I have a similar issue in TC10.0:
Log Output: 6 skipped, 118 passed, 124 total
Reports as 109 Tests passed

Then someone checked in an it.only-statement, halving the number of actual run tests, which should have triggered a warning in Teamcity, but the reporter reported an increase in the number of tests:

Log Output: 69 skipped, 59 passed, 128 total
Reports as 113 Tests passed

**Comment by bumbu** [comment] 2017-06-20 13:21
Same issue with TeamCity Enterprise 2017.1.1

**Comment by tmeador-dl** [comment] 2017-06-25 19:22
It looks like this might be happening because only the it statement descriptions are being reported, and not the combined describe/it descriptions. For instance I have multiple it statements that read 'should have property theSameProperty' but in different describe blocks. These tests are showing up in TeamCity as a single test with multiple run counts. (TeamCity Enterprise 10.0.2.)

**Comment by Ant-VAV** [comment] 2017-08-15 07:01
Same issue with TeamCity Enterprise 2017.1.2

**Comment by Ant-VAV** [comment] 2017-08-15 08:03
As one of possible methods to solve this issue: https://github.com/winterbe/jest-teamcity-reporter/pull/16

**Closed as completed** 2017-08-23 12:07 UTC

**Comment by winterbe** [comment] 2017-08-23 12:14
I just published the fix from @Ant-VAV (thanks for that). Please test again with version 0.7.0 to verify that the problem is solved.
